/*
** types.h for epitech in /home/chapui_s/rendu/
**
** Made by chapui_s
** Login   <chapui_s@epitech.eu>
**
** Started on  Mon May  4 23:49:29 2015 chapui_s
** Last update Mon May  4 23:52:34 2015 chapui_s
*/

#ifndef TYPES_H_
# define TYPES_H_

# define SSIZE_T	(1)
# define INT	(2)
# define VOID_P	(3)
# define SIZE_T	(4)
# define CONST_VOID_P	(5)
# define CONST_CHAR_P	(6)
# define STRUCT_P	(7)
# define STRUCT_STAT_P	(8)
# define STRUCT_FD_P	(9)
# define NFDS_T	(10)
# define OFF_T	(11)
# define PVOID	(12)
# define UNSIGNED_LONG	(13)
# define VARGS	(14)
# define CONST_STRUCT_IOVEC_P	(15)
# define FD_SET_P	(16)
# define STRUCT_TIMEVAL_P	(17)
# define VOID	(18)
# define UNSIGNED_CHAR_P	(19)
# define KEY_T	(20)
# define STRUCT_SHMID_DS_P	(21)
# define CONST_STRUCT_TIMESPEC_P	(22)
# define STRUCT_TIMESPEC_P	(23)
# define STRUCT_ITIMERVAL_P	(24)
# define UNSIGNED_INT	(25)
# define CONST_STRUCT_ITIMERVAL_P	(26)
# define PID_T	(27)
# define OFF_T_P	(28)
# define CONST_STRUCT_SOCKADDR_P	(29)
# define SOCKLEN_T	(30)
# define STRUCT_SOCKADDR_P	(31)
# define SOCKLEN_T_P	(32)
# define CONST_STRUCT_MSGHDR_P	(33)
# define STRUCT_MSGHDR_P	(34)
# define CHAR_P_CONST	(35)
# define INT_P	(36)
# define STRUCT_RUSAGE_P	(37)
# define STRUCT_UTSNAME_P	(38)
# define STRUCT_SEMBUF_P	(39)
# define LONG	(40)
# define STRUCT_MSQID_DS_P	(41)
# define STRUCT_LINUX_DIRENT_P	(42)
# define PCHAR	(43)
# define CHAR_P	(44)
# define MODE_T	(45)
# define UID_T	(46)
# define GID_T	(47)
# define STRUCT_TIMEZONE_P	(48)
# define STRUCT_RLIMIT_P	(49)
# define CLOCK_T	(50)
# define STRUCT_TMS_P	(51)
# define ENUM_____REQUEST	(52)
# define CONST_GID_T_P	(53)
# define UID_T_P	(54)
# define GID_T_P	(55)
# define CAP_USER_HEADER_T	(56)
# define CAP_USER_DATA_T	(57)
# define CONST_CAP_USER_DATA_T	(58)
# define SIGINFO_T_P	(59)
# define CONST_STACK_T_P	(60)
# define STACK_T_P	(61)
# define CONST_STRUCT_UTIMBUF_P	(62)
# define DEV_T	(63)
# define STRUCT_STATFS_P	(64)
# define ID_T	(65)
# define CONST_STRUCT_SCHED_PARAM_P	(66)
# define STRUCT_SCHED_PARAM_P	(67)
# define STRUCT_TIMESPEC_P_	(68)
# define STRUCT____ARGS_P	(69)
# define STRUCT_TIMEX_P	(70)
# define CONST_STRUCT_RLIMIT_P	(71)
# define CONST_STRUCT_TIMEVAL_P	(72)
# define CONST_STRUCT_TIMEZONE_P	(73)
# define CADDR_T	(74)
# define STRUCT_KERNEL_SYM_P	(75)
# define SIZE_T_P	(76)
# define STRUCT_NFSCTL_ARG_P	(77)
# define UNION_NFSCTL_RES_P	(78)
# define OFF64_T	(79)
# define TIME_T	(80)
# define _T___T_P	(81)
# define CONST_CPU_SET_T_P	(82)
# define CPU_SET_T_P	(83)
# define STRUCT_USER_DESC_P	(84)
# define UNSIGNED	(85)
# define AIO_CONTEXT_T_P	(86)
# define AIO_CONTEXT_T	(87)
# define STRUCT_IO_EVENT_P	(88)
# define STRUCT_IOCB_P	(89)
# define U64	(90)
# define STRUCT_LINUX_DIRENT64_P	(91)
# define CLOCKID_T	(92)
# define STRUCT_SIGEVENT_P	(93)
# define TIMER_T_P	(94)
# define TIMER_T	(95)
# define CONST_STRUCT_ITIMERSPEC_P	(96)
# define STRUCT_ITIMERSPEC_P	(97)
# define STRUCT_EPOLL_EVENT_P	(98)
# define CONST_STRUCT_TIMEVAL	(99)
# define CONST_UNSIGNED_LONG_P	(100)
# define UNSIGNED_LONG_P	(101)
# define MQD_T	(102)
# define UNSIGNED_INT_P	(103)
# define CONST_STRUCT_SIGEVENT_P	(104)
# define STRUCT_MQ_ATTR_P	(105)
# define STRUCT_KEXEC_SEGMENT_P	(106)
# define IDTYPE_T	(107)
# define KEY_SERIAL_T	(108)
# define UINT32_T	(109)
# define STRUCT_POLLFD_P	(110)
# define CONST_SIGSET_T_P	(111)
# define STRUCT_ROBUST_LIST_HEAD_P	(112)
# define LOFF_T_P	(113)
# define CONST_INT_P	(114)
# define CONST_STRUCT_TIMESPEC	(115)
# define STRUCT_PERF_EVENT_ATTR_P	(116)
# define STRUCT_MMSGHDR_P	(117)
# define UINT64_T	(118)
# define STRUCT_FILE_HANDLE_P	(119)
# define UNSIGNED_P	(120)
# define STRUCT__CACHE_P	(121)
# define CONST_STRUCT_SCHED_ATTR_P	(122)
# define STRUCT_SCHED_ATTR_P	(123)

#endif /* !TYPES_H_ */
